services:
  - type: web
    name: zahran-backend
    env: python
    buildCommand: cd "nvoice System/backend" && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd "nvoice System/backend" && gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: zahran-db
          property: connectionString

databases:
  - name: zahran-db
    databaseName: zahran_db
    user: zahran_user
